### ISSUE TITLE
Создать базовую структуру приложения

### ISSUE THREAD

**Issue by sylvix** [ESDP-JS-2020-1/caravan#1]
### Мотивация
Необходимо создать базовую структуру приложения, чтобы все участники проекта могли ее склонировать и начинать работу над своими задачами.

### Конечный результат
backend-приложение с базовыми настройками, а также frontend-приложение с установленными библиотеками и настроенным redux-хранилищем. Также добавить material UI 

### Критерии приемки

```gherkin
Допустим я зашел в репозиторий проекта
И склонировал проект
То я вижу базовую структуру приложения
```

### Оценка
Планируемое время: 1 час

**Comment by Baytik** [comment]
Создал базовую структуру приложения

**Comment by spartakF300** [comment]
Мотивация
Необходимо создать базовую структуру логина пользователя на фронтенде,а так же  на бэкэнде.
Конечный результат
Пользователь может логиниться в приложение, а также имеет возможность разлогиниться.

Критерии приемки
допустим я ввожу логин и пароль в форму регистрации, после нажатия на кнопку логин, пользователь должен быть залогинен и переброшен на главную страницу. На главной странице должно отображаться имя пользователя и аватар.
Оценка
Планируемое время 3часа

**Comment by spartakF300** [comment]
Мотивация
Необходимо создать базовую структуру логина пользователя на фронтенде,а так же на бэкэнде.
Конечный результат
Пользователь может логиниться в приложение, а также имеет возможность разлогиниться.

Критерии приемки
допустим я ввожу логин и пароль в форму регистрации, после нажатия на кнопку логин, пользователь должен быть залогинен и переброшен на главную страницу. На главной странице должно отображаться имя пользователя и аватар.
Оценка
Планируемое время 3часа
