### ISSUE TITLE
№10 изменить список продуктов на табличный и добавить image к продукту

### ISSUE THREAD

**Issue by WinkOne** [ESDP-JS-2020-1/caravan#10]
###Мотивация
Необходимо доработать список продуктов(добавить image и переделать в табличный вид)
###Конечный результат
Список продуктов в табличной системе с фотографией продукта

###Критерии приёмки
Допустим я зарегистрирован как администратор
И нахожусь на странице Добавление продуктов
И заполняю форму добавления продукта  
И нажимаю на кнопку Сохранить 
Тогда  перехожу на страницу продуктов

###Оценка
Планируемое время 1.5 часа

**Comment by notanITspecialist** [comment]
Выполнил тикет
