### ISSUE TITLE
Сделать увеличение картинки у продукта, при наведении на неё мышкой

### ISSUE THREAD

**Issue by Baytik** [ESDP-JS-2020-1/caravan#105]
**Мотивация**
Необходимо сделать увеличение картинки у продукта, при наведении. Чтобы пользователю было удобно смотреть что это за продукт

**Конечный результат**
При просмотре страницы продуктов а так же при наведении мышки на картину нужно чтобы картина увеличивалось

**Критерий приемки**
```gherkin
Допустим я нахожусь на странице продуктов
То при наведении мышкой на картину картина увеличивается
```
**Оценка**
Планируемое время: 2 часа

**Comment by Ulan1983** [comment]
выполнил за 1,5 часа
