### ISSUE TITLE
Добавить возможность администратору добавлять критерии авто экспедитора 

### ISSUE THREAD

**Issue by KadyrPoyraz228337** [ESDP-JS-2020-1/caravan#11]
### Мотивация
Необходимо создать возможность администратору добавлять критерии для авто экспедиторов

### Конечный результат
Всплывающие поля формы после выбора роди экспедитора с названием марки авто ,грузоподъёмностью в м³ и чекбоксом на наличие холодильника в машине
 
### Критерии приемки

```gherkin
Допустим я зарегистрирован как администратор
И нахожусь на странице добавления нового пользователя
То я заполняю поля формы 
И выбираю роль "courier"
И заполняю поля формы
И нажимаю на кнопку  "Добавить"
То я вижу текст после добавления "Пользователь добавлен успешно"
```

### Оценка
Планируемое время: 3 час

**Comment by notanITspecialist** [comment]
Начал в 11:17
Закончил в 11:48
