### ISSUE TITLE
Переделать все функции которые выполняют роль удаления

### ISSUE THREAD

**Issue by Baytik** [ESDP-JS-2020-1/caravan#110]
**Мотивация**
Необходимо переделать все функции которые выполняют роль удаления, с бекенда

**Конечный результат**
При логине на сайт, то вижу что ни какие элементы нельзя удалять

**Критерий приемки**
```gherkin
Допустим я залогинен как администратор
То при попытке удалить ничего не получиться
```
**Оценка**
Планируемое время: 4 часа

**Comment by KadyrPoyraz228337** [comment]
Выполнил за 1 час 30 минут
