### ISSUE TITLE
Исправить ошибку с неверной отправкой (404 ошибки в groups.js:16) 

### ISSUE THREAD

**Issue by WinkOne** [ESDP-JS-2020-1/caravan#111]
### Мотивация
Необходимо исправить неверную отправку ошибки с 404 на 500, т.к 
groups.js:16 - 404 ошибку неверно отправлять в этой ситуации, т.к. если ничего не найдено, вернется пустой список. А если сработает catch, это ошибка БД, и надо отправлять 500 ошибку.
### Конечный результат
При не правильном запросе должна отправляться 500 статус ошибки 
**Критерии приёмки**
```gherkin
Допустим я отправляю неверный запрос  
То я вижу 500 статус ошибки 
 ```
### Оценка 
Планируемое время 1 час

**Comment by Ulan1983** [comment]
Выполнил за 40 минут
