### ISSUE TITLE
Исправить requests.js:116

### ISSUE THREAD

**Issue by WinkOne** [ESDP-JS-2020-1/caravan#117]
### Мотивация 
Необходимо исправить так как
Неоптимально делать await-ами в цикле поиск в базе. Можно было запросить все товары через $in, потом пройтись по найденному массиву - это быстрее, чем делать много запросов в базу в цикле.

### Конечный результат 
Нужно чтобы можно было запросить все товары через $in, потом пройтись по найденному массиву - это быстрее, чем делать много запросов в базу в цикле.

### Оценка
 1 час

**Comment by spartakF300** [comment]
выполнил за 3 часа
