### ISSUE TITLE
Найти непереведенные слова и перевести их на кыргызский язык

### ISSUE THREAD

**Issue by WinkOne** [ESDP-JS-2020-1/caravan#122]
### Мотивация 
Необходимо найти не переведенные слова и перевести их с русского на кыргызский 
### Конечный результат
Все слова в приложении должны иметь возможнесть переводится с руского на кыргызский и наобород 
### Оценка 
30 мин

**Comment by Ulan1983** [comment]
Выполнил за 30 мин
