### ISSUE TITLE
Реализовать правильное отображение ошибок на фронте 

### ISSUE THREAD

**Issue by WinkOne** [ESDP-JS-2020-1/caravan#125]
### Мотивация 
Необходимо сделать правильное отображение ошибок на фронте 
###  Конечный результат 
Я ввожу в поля форм неверные данные и вижу четкое отображение ошибочного запроса 

### Критерий приемки
```gherkin
Допустим я нахожусь на странице логин
И ввожу неверные данные 
То я вижу четкое отображение ошибочного запроса 
```
### Оценка 
2 часа

**Comment by KadyrPoyraz228337** [comment]
Выполнил за 3 часа
