### ISSUE TITLE
Сделать тесты для 11 тикета

### ISSUE THREAD

**Issue by KadyrPoyraz228337** [ESDP-JS-2020-1/caravan#13]
### Мотивация
Необходимо создать тесты для добавления выбора критериев авто экспедитора, при регистрации администратором 

### Конечный результат
Тесты с реализованной проверкой функционала 11 тикета

```gherkin
Допустим я запустил команду npm start в тестах
Тогда я не должен увидеть ошибок в конечном результате
```

### Оценка
Планируемое время 1 часа

**Comment by notanITspecialist** [comment]
Начал в 15:58
Закончил 12:17
