### ISSUE TITLE
Зафиксировать список всех пермишнов в виде констант.

### ISSUE THREAD

**Issue by spartakF300** [ESDP-JS-2020-1/caravan#130]
Мотивация
Необходимо зафиксировать список всех пермишнов в виде констант, чтобы потом не запутаться и сохранить их все в каком-то отдельном файле (напр. permissions.js - const CREATE_USER_PERMISSION = 'createUser') и т.п. - потом использовать эти константы вместо "магических строк".

Конечный результат
Зафиксировать список всех пермишнов в виде констант.

Оценка
Планируемое время: 1 часа

**Comment by WinkOne** [comment]
закончил за 1 час
