### ISSUE TITLE
Исправить тесты

### ISSUE THREAD

**Issue by spartakF300** [ESDP-JS-2020-1/caravan#131]
### Мотивация
Необходимо исправить слишком длинные сценарии. В сценарии должно быть три-четыре предложения. 
Сценарии и степы можно и нужно разбивать на файлы.

### Конечный результат
 Сценарии должны быть три-четыре предложения. 
Степы  разбиты на файлы.

### Оценка
Планируемое время: 1.5 часа

**Comment by KadyrPoyraz228337** [comment]
Выполнил за 1.5 часа
