### ISSUE TITLE
Добавления пользователя в группу при регистрации нового пользователя.

### ISSUE THREAD

**Issue by spartakF300** [ESDP-JS-2020-1/caravan#133]
### Мотивация
Необходимо реализовать возможность добавления пользователя в группу при регистрации нового пользователя.

### Конечный результат
Когда я зайду на страницу добавления нового пользователя то я должен иметь возможность добавить пользователя в группу.

### Критерий приемки
```gherkin
Допустим я нахожусь на странице добавления нового пользователя 
То я вижу поле с возможностью выбора группы
```
### Оценка
Примерно 2 часа

**Comment by Baytik** [comment]
Выполнил за 3 часа
