### ISSUE TITLE
Исправить отображения списка заявок на мобильных устройствах

### ISSUE THREAD

**Issue by spartakF300** [ESDP-JS-2020-1/caravan#136]
Мотивация
Необходимо сделать визуальное отображения списка заявок для мобильных устройств

Конечный результат
Когда я зайду с мобильного устройства на страницу просмотра списка заявок, то все должно выглядеть корректно

Оценка
2 часа

**Comment by Ulan1983** [comment]
Выполнил за 2,5 часа
