### ISSUE TITLE
Реализовать категории у пользователей и тесты к ним

### ISSUE THREAD

**Issue by KadyrPoyraz228337** [ESDP-JS-2020-1/caravan#14]
### Мотивация
Необходимо создать сайдбар в списке пользователей с ролями пользователей

### Конечный результат
Сайдбар в списке пользователей с ролями, при переходе по ссылкам которого в списке должны отображаться только пользователи с текущей ролью

### Критерии приёмки
```gherkin
Допустим я зарегистрирован как администратор
И нахожусь на списке пользователей
Если я перейду по категории "courier"
Тогда я вижу текст "Курьеры"
```

### Оценка
Планируемое время 3.5 часа

**Comment by notanITspecialist** [comment]
Начал в 13:05
Закончил в 13:30

**Comment by notanITspecialist** [comment]
Не реализовал отображение всех присущих свойст роли в таблице

**Comment by notanITspecialist** [comment]
Начал в 13:05
Закончил в 13:52
