### ISSUE TITLE
Убрать все actions, actioncreators и reducers, связанные с выводом прелоадера

### ISSUE THREAD

**Issue by KadyrPoyraz228337** [ESDP-JS-2020-1/caravan#151]
### Мотивация
Необходимо убрать все actions, actioncreators и reducers, связанные с выводом прелоадера за ненадобностью их использования в компонентах

### Конечный результат
Приложение, отчищенное от не нужных екшенов и т.д и т.п

### Оценка
Планируемое время:1 час

**Comment by Baytik** [comment]
Заняло 40 мин
