### ISSUE TITLE
Улучшить внешний вид информации о заявке

### ISSUE THREAD

**Issue by KadyrPoyraz228337** [ESDP-JS-2020-1/caravan#152]
### Мотивация
Необходимо улучшить внешний вид информации о заявке. Нужно вынести назначение экспедитору в отдельное модальное окно. Вынести список продуктов во всплывающий список

### Конечный результат
Переделанная страница информации о заявке с улучшенной визуальной составляющей

### Оценка
Планируемое время: 3 часа

**Comment by spartakF300** [comment]
закончил за 3 часа
