### ISSUE TITLE
Исправить отображение пользовательского интерфейса 

### ISSUE THREAD

**Issue by KadyrPoyraz228337** [ESDP-JS-2020-1/caravan#155]
### Мотивация
Необходимо исправить отображение пользовательского интерфейса в зависимости от наличия разрешений у конкретного пользователя 

### Конечный результат
Пользователям с определёнными пермишенами видит только те элементы интерфейса, к которым у него есть доступ

### Оценка
Планируемое время: 2 часа

**Comment by Baytik** [comment]
Заняло 3 часа
