### ISSUE TITLE
Дать возможность пользователям с разрешением удалять заявки после того, как они были закрыты 

### ISSUE THREAD

**Issue by KadyrPoyraz228337** [ESDP-JS-2020-1/caravan#156]
### Мотивация 
Необходимо дать возможность пользователям с разрешением удалять заявки после того, как они были закрыты 

### Конечный результат
Пользователи с нужными разрешениями имеют возможность удалить заявку

### Критерии приёмки 
```gherkin
Допустим я зарегистрирован как администратор
И нахожусь на странице списка заявок
И нажимаю на кнопку "edit"
И нажимаю на кнопку "#remove"
И нажимаю на кнопку "#yes"
Тогда я вижу текст "Заявка успешно удалена"
```

### Оценка
Планируемое время: 30 минут

**Comment by Baytik** [comment]
Заняло 1 час
