### ISSUE TITLE
Изменить добавление продуктов 

### ISSUE THREAD

**Issue by Ulan1983** [ESDP-JS-2020-1/caravan#164]
**Мотивация**
Необходимо изменить добавление продуктов для более удобного использования 

**Конечный результат**
В добавлении продуктов поле выбора типа продукта является autocomplete с возможностью выбора нового типа 

**Критерии приёмки**
```gherkin
Допустим я залогинен как администратор
И я нахожусь на странице добавления продуктов
И я заполняю поля формы
Тогда по нажатию кнопки добавить добавляется новый продукт
```
**Оценка**
Планируемое время: 1 час

**Comment by Baytik** [comment]
Заняло 1 час 30 мин
