### ISSUE TITLE
Исправить редактирование пользователя и продуктов в backend

### ISSUE THREAD

**Issue by Baytik** [ESDP-JS-2020-1/caravan#167]
**Мотивация**
Необходимо изменить редактирование пользователя и продуктов, так чтобы при редактировании с картиной старая картина удалялась из базы

**Конечный результат**
При редактировании пользователя и продуктов старая картина удаляется и на место подставляется новая

**Критерии приёмки**
```gherkin
Допустим я залогинен как администратор
И я нахожусь на странице редактировании продукта
И я заполняю поля формы с картиной
Тогда я вижу что на сервере предыдущая картина удалилась и за место неё подставилась новая
```
**Оценка**
Планируемое время: 3 часа

**Comment by spartakF300** [comment]
выполнил за 3 часа
