### ISSUE TITLE
Убрать все ошибки в консоли

### ISSUE THREAD

**Issue by Baytik** [ESDP-JS-2020-1/caravan#169]
**Мотивация**
Необходимо убрать все ошибки в консоли

**Конечный результат**
При входе на сайт не должно быть ошибок в консоли

**Критерии приёмки**
```gherkin
Допустим я захожу на сайт
И открываю консоль
Тогда я вижу что на консоли всё чисто и без ошибок
```
**Оценка**
Планируемое время: 2 часа

**Comment by Ulan1983** [comment]
выполнил за 1 ч 30 мин
