### ISSUE TITLE
Реализовать редактирование данных авто курьера

### ISSUE THREAD

**Issue by KadyrPoyraz228337** [ESDP-JS-2020-1/caravan#17]
### Мотивация
Необходимо добавить редактирование данных авто курьера 

### Конечный результат
При редактировании курьера есть возможность редактировать данные об его авто 

### Критерии приёмки
```gherkin
Допустим я зарегистрирован как администратор 
И нахожусь на странице редактирования пользователя
То я заполняю поля формы
И выбираю роль "courier"
И заполняю поля данных об авто
И нажимаю на кнопку "Редактировать"
Тогда я вижу текст "Пользователь добавлен успешно"
```

### Оценка
Планируемое время 40 минут

**Comment by notanITspecialist** [comment]
Начал в 16:02
Закончил в 16:10
