### ISSUE TITLE
Перевести на киргизский язык не переведённые слова

### ISSUE THREAD

**Issue by Baytik** [ESDP-JS-2020-1/caravan#171]
**Мотивация**
Необходимо перевести на киргизский язык не переведённые слова,
Пример страница Истории, Статистика, итд

**Конечный результат**
При входе на сайт вижу что все слова переведены на киргизский язык

**Критерии приёмки**
```gherkin
Допустим я захожу на сайт
И меняю язык приложения с русского на киргизский
Тогда я вижу что все слова переведены на киргизский язык
```
**Оценка**
Планируемое время: 1 час

**Comment by Ulan1983** [comment]
Выполнил за 1 ч 30 мин
