### ISSUE TITLE
Необходимо при просмотре пользователя, дать ссылку увидеть все его заказы продуктов

### ISSUE THREAD

**Issue by Baytik** [ESDP-JS-2020-1/caravan#173]
**Мотивация**
Необходимо при просмотре пользователя, дать ссылку увидеть все его заказы продуктов

**Конечный результат**
Есть возможность увидеть заказы продуктов который делал пользователь

**Критерии приёмки**
```gherkin
Допустим я просматриваю данные о пользователе
То я вижу ссылку которая ведёт к просмотру заказов который делал данный пользователь
```
**Оценка**
Планируемое время: 2 часа

**Comment by spartakF300** [comment]
выполнил за 3 часа
