### ISSUE TITLE
Нужно исправить удаление пользователя из группы

### ISSUE THREAD

**Issue by Baytik** [ESDP-JS-2020-1/caravan#174]
**Мотивация**
Необходимо исправить удаление пользователя из группы

**Конечный результат**
Удаление пользователя из группы работает без ошибок и проблем

**Критерии приёмки**
```gherkin
Допустим я на странице групп
И удаляю пользователя из группы
Тогда я вижу что пользователь успешно удалён из группы
```
**Оценка**
Планируемое время: 30 мин

**Comment by KadyrPoyraz228337** [comment]
Выполнил за 30 минут
