### ISSUE TITLE
Исправить редактирование продукта

### ISSUE THREAD

**Issue by Ulan1983** [ESDP-JS-2020-1/caravan#180]
**Мотивация**
Необходимо исправить редактирование продукта

**Конечный результат**
Редактирование продукта отрабатывает корректно

**Критерии приёмки**
```gherkin
Допустим я залогинен как админ
И перехожу на страницу редактирования продукта
И я заполняю поля формы
То редактирование продукта отрабатывает без ошибок 
```
**Оценка**
Планируемое время: 2 часа

**Comment by Baytik** [comment]
Заняло 1 час
