### ISSUE TITLE
Сделать возможность для загрузки приложения на телефон экспедитора

### ISSUE THREAD

**Issue by Ulan1983** [ESDP-JS-2020-1/caravan#181]
**Мотивация**
Необходимо сделать возможность для загрузки приложения на телефон экспедитора для более удобной работы 

**Конечный результат**
Есть возможность закачать приложение на телефон (IOS, Android)

**Критерии приёмки**
```gherkin
Допустим я залогинен как экспедитор
То у меня есть возможность загрузить это приложение себе на смартфон
```
**Оценка**
Планируемое время: 1 час

**Comment by KadyrPoyraz228337** [comment]
Выполнмл за 1 час
