### ISSUE TITLE
Убрать консоли ненужные кнопки и перевести сайт до конца

### ISSUE THREAD

**Issue by Baytik** [ESDP-JS-2020-1/caravan#185]
### Мотивация 
Необходимо убрать консоли ненужные кнопки и перевести сайт до конца
Пример у нас ещё есть на англ.языке слова

### Конечный результат 
Приложение работает без проблем, все слова будут переведены а так же кнопки которые не нужны они исчезнут

### Оценка
Планируемое время 3 часа

**Comment by Ulan1983** [comment]
закончил за 1 ч 30 мин
