### ISSUE TITLE
Создать логин пользователя.

### ISSUE THREAD

**Issue by spartakF300** [ESDP-JS-2020-1/caravan#2]

**Comment by spartakF300** [comment]
Мотивация
Необходимо создать базовую структуру логина пользователя на фронтенде,а так же на бэкэнде.
Конечный результат
Пользователь может логиниться в приложение, а также имеет возможность разлогиниться.

Критерии приемки
допустим я ввожу логин и пароль в форму регистрации, после нажатия на кнопку логин, пользователь должен быть залогинен и переброшен на главную страницу. На главной странице должно отображаться имя пользователя и аватар.
Оценка
Планируемое время 3часа

**Comment by spartakF300** [comment]
### Мотивация
Необходимо создать базовую структуру логина пользователя на фронтенде,а так же на бэкэнде.
### Конечный результат
Пользователь может логиниться в приложение, а также имеет возможность разлогиниться.

### Критерии приемки
допустим я ввожу логин и пароль в форму регистрации, после нажатия на кнопку логин, пользователь должен быть залогинен и переброшен на главную страницу. На главной странице должно отображаться имя пользователя и аватар.
### Оценка
Планируемое время 3часа

**Comment by KadyrPoyraz228337** [comment]
Выполнили тикет за 1.5 час
