### ISSUE TITLE
Сделать редактирование заявки администратором и оператором

### ISSUE THREAD

**Issue by KadyrPoyraz228337** [ESDP-JS-2020-1/caravan#21]
### Мотивация
Необходимо сделать возможность редактирования заявки для оператора и администратора с возможностью редактирования текущей заявки и добавления новых продуктов в неё

### Конечный результат
На странице редактирования отображается информация о текущей заявке, после изменения которой и нажатия кнопки "Изменить", данные заявки меняются и отображаются в списке заявок

### Критерии приёмки
```gherkin
Допустим я зарегистрирован как администратор
И нахожусь на странице редактирования 
И заполняю поля формы
И нажимаю на кнопку "Изменить"
Тогда я вижу текст "Заявка изменена"
```

### Оценка
Планируемое время 2 часа

**Comment by WinkOne** [comment]
Спартак выполнил тикет за 4 часа
