### ISSUE TITLE
Переделать меню приложения под выдвигающееся меню

### ISSUE THREAD

**Issue by KadyrPoyraz228337** [ESDP-JS-2020-1/caravan#22]
### Мотивация
Необходимо создать выдвигающееся слева меню и перенести туда все элементы из  всплывающего меню

### Конечный результат
Меню "бургер", по нажатию на которое открывается всплывающее меню с ссылками

### Оценка
Планируемое время 2 часа

**Comment by WinkOne** [comment]
делал 1 час
