### ISSUE TITLE
Переделать поле названия продукта в добавлении заявки в autocomplite 

### ISSUE THREAD

**Issue by KadyrPoyraz228337** [ESDP-JS-2020-1/caravan#24]
### Мотивация
Необходимо заменить текстовое поля ввода названия продукта, на autocomplite с возможностью поиска любого продукта по его названию

### Конечный результат
Autocomplite в добавлении заявки с поиском конкретного продукта по названию 

### Критерии приемки

```gherkin
Допустим я зарегистрирован как администратор
И нахожусь на странице добавления заявки
И заполняю поля формы
И нажимаю на кнопку "Создать заявку" 
То я вижу текст "Заявка создана успешно"
```

### Оценка
Планируемое время: 1.5 часа

**Comment by Ulan1983** [comment]
Выполнил за 1,5 часа
