### ISSUE TITLE
Сделать модальное окно отдельным компонентом

### ISSUE THREAD

**Issue by KadyrPoyraz228337** [ESDP-JS-2020-1/caravan#26]
### Мотивация
Необходимо создать компонент модального окна с возможностью передать children компоненты в body модального окна

### Конечный результат
Готовый, функционирующий компонент модального окна, который можно использовать в разных контекстах и ситуациях в приложении

### Оценка
Планируемое время: 40 минут

**Comment by Baytik** [comment]
Начал выполнять в 15:18
Закончил выполнение в 15:47
