### ISSUE TITLE
Переделать все модальные окна приложения под кастомное модальное окно

### ISSUE THREAD

**Issue by KadyrPoyraz228337** [ESDP-JS-2020-1/caravan#27]
### Мотивация
Необходимо переделать все модальные окна приложения на кастомное модальное окно в целях избежания дублирования кода

### Конечный результат
Кастомное модальное окно, использованное во всех местах приложения, где это необходимо

### Оценка
Планируемое время: 30 минут

**Comment by Baytik** [comment]
Сделал за 30 мин
