### ISSUE TITLE
Перенести все экшен типы в отдельный фал actionsTypes.js

### ISSUE THREAD

**Issue by KadyrPoyraz228337** [ESDP-JS-2020-1/caravan#28]
### Мотивация
Необходимо перенести все экшен типы в отдельный файл для более удобного написания кода 

### Конечный результат
Файл actionsTypes со всеми типами экшенов со всего приложения 

### Критерии приемки
```gherkin
Допустим я открыл проект
И я захожу в директорию store
И я захожу в директорию actions
Тогда я вижу файл actionsTypes.js со всеми типами экшенов
```

### Оценка
Планируемое время: 30 минут

**Comment by Ulan1983** [comment]
Выполнил за 30 минут
