### ISSUE TITLE
Сделать отображение создания нового продукта в истории

### ISSUE THREAD

**Issue by KadyrPoyraz228337** [ESDP-JS-2020-1/caravan#29]
### Мотивация
Необходимо создать отображение добавление продуктов в истории 

### Конечный результат
При добавлении нового продукта, в истории должно отображаться кто создал продукт, какой создал продукт, в какое время и не обязательный комментарий. При добавлении списка продуктов, в истории должен отразится каждый продукт 

### Критерии приемки

```gherkin
Допустим я зарегистрирован как администратор
И создал продукт n
Тогда в истории я должен увидеть, что я создал продукт n во время n
```

### Оценка
Планируемое время: 30 мин

**Comment by Ulan1983** [comment]
Выполнил тикет за 1 час
