### ISSUE TITLE
Добавление пользователей администратором, вывод списка зарегистрированных пользователей

### ISSUE THREAD

**Issue by spartakF300** [ESDP-JS-2020-1/caravan#3]
**Мотивация**

Необходимо сделать возможность добавления пользователей администратором и вывод всех зарегистрированных пользователей.

**Конечный результат**

Администратор имеет возможность зарегистрировать нового пользователя и получать список всех пользователей.

**Критерии приемки**

допустим я заполнил все поля формы,при выборе роли "Market" должны появляться два дополнительных поля "marketName" и "address". после нажатия на кнопку регистрации, пользователь должен быть зарегистрирован и переброшен на  страницу со списком всех пользователей. На странице пользователей должен отобразиться добавленный пользователь.

**Оценка**

Планируемое время 3 часа.

**Comment by KadyrPoyraz228337** [comment]
Выполнил тикет за 4.5 часа
