### ISSUE TITLE
Сделать bash скрипт для запуска тестов

### ISSUE THREAD

**Issue by KadyrPoyraz228337** [ESDP-JS-2020-1/caravan#31]
### Мотивация
Необходимо создать bash скрипт для запуска фикстур сервера, запуска dev сервера на отдельном порте и запуска client приложения на отдельном порте

### Конечный результат
Тесты с возможностью полноценной работы после запуска одного скрипта, без надобности отдельно запускать фикстуры и сервер с client приложением на отдельных портах

### Критерии приемки
```gherkin
Допустим я открыл папку с тестами приложения
И запустил команду npm start
То я вижу как отрабатывают тесты
```

### Оценка
Планируемое время: 1.5 часа

**Comment by Baytik** [comment]
Заняло 1 час 10 мин
