### ISSUE TITLE
Исправить баг при удалении продукта

### ISSUE THREAD

**Issue by KadyrPoyraz228337** [ESDP-JS-2020-1/caravan#33]
### Мотивация
Необходимо исправить баг, который заключается в том, что при добавления комментария в историю, комментарий не отображается 

### Конечный результат
При удалении продукта, если добавить комментарий, то в истории отобразится кто удалил продукт, когда и комментарий

### Критерии приемки
```gherkin
Допустим я зарегистрирован как администратор
И я нахожусь на странице редактирования продукта
И я нажимаю на кнопку "Удалить"
И я нажимаю на кнопку "Да"
Тогда я вижу текст "Продукт успешно удалён"
```

### Оценка
Планируемое время: 30 мин

**Comment by Baytik** [comment]
Начал в 15:00
Закончил 15:30
