### ISSUE TITLE
Добавить возможность администратору добавлять заявки

### ISSUE THREAD

**Issue by KadyrPoyraz228337** [ESDP-JS-2020-1/caravan#35]
### Мотивация
Необходимо дать возможность администратору добавлять заявки

### Конечный результат
У администратора, по аналогии с пользователем с ролью "market" есть возможность добавлять заявки

### Критерии приемки
```gherkin
Допустим я зарегистрирован как администратор
И нахожусь на странице добавления заявки
Если я заполняю поля формы
И нажимаю на кнопку "Создать заявку"
Тогда я вижу текст "Заявка создана успешно"
```

### Оценка
Планируемое время: 20 минут

**Comment by Ulan1983** [comment]
Выполнил за 30 мин
