### ISSUE TITLE
Переделать неработающие тесты

### ISSUE THREAD

**Issue by Ulan1983** [ESDP-JS-2020-1/caravan#38]
**Мотивация**
Необходимо переделать неработающие тесты в связи с изменениями в приложении 

**Конечный результат**
Все тесты работают без нареканий

**Критерии приемки**
```gherkin
Допустим я нахожусь на порту запуска тестов
Если я запускаю команду прогона тестов
То все тесты запускаются без нареканий
```
**Оценка**
Планируемое время: 2 часа

**Comment by Baytik** [comment]
Заняло 2 часа времени
