### ISSUE TITLE
При создании продукта дать возможность указать обязательность наличия холодильника при транспортровке товара

### ISSUE THREAD

**Issue by Ulan1983** [ESDP-JS-2020-1/caravan#39]
**Мотивация**
Дать возможность указать обязательность наличия холодильника. Также необходимо переделать  список показа продуктов и редактирование продукта

**Конечный результат**
У пользователя при создании продукта есть возможность указать необходимость наличия холодильника. При показе списка продуктов появляется новое поле "наличие холодильника" и в редактировании продукта также появляется новое поле "наличие холодильника"

**Критерии приемки**
```gherkin
Допустим я зарегистрирован как администратор
И нахожусь на странице добавления продукта
Если я заполняю поля формы
И вижу поле "наличие холодильника"
И я отмечаю галочкой это поле
И нажимаю на кнопку "Сохранить"
То продукт создается успешно 
```
Оценка
Планируемое время: 2,5 часа

**Comment by KadyrPoyraz228337** [comment]
Закончил за 1.5
