### ISSUE TITLE
Добавить  редактирование пользователей

### ISSUE THREAD

**Issue by spartakF300** [ESDP-JS-2020-1/caravan#4]
**Мотивация**

Реализовать возможность администратору редактировать пользователей.

**Конечный результат**

Администратор может редактировать информацию пользователей.

**Критерии приемки**

Допустим я перехожу на страницу редактирования пользователя.
Поля Формы должны быть заполнены информацией о редактируемом пользователе.
При выборе роли "Market" должны появляться два дополнительных поля "marketName" и "address"
При нажатие на кнопку редактирования, пользователь должен быть отредактирован и переброшен на страницу со списком пользователей где должен появиться отредактированный пользователь.

**Оценка**
Планируемое время 1.5 часа

**Comment by notanITspecialist** [comment]
Выполнил задачу за 3 часа
