### ISSUE TITLE
Сделать отображение карты в приложении

### ISSUE THREAD

**Issue by Ulan1983** [ESDP-JS-2020-1/caravan#41]
**Мотивация**
Необходимо сделать отображение карты в приложении

**Конечный результат**
При переходе на страницу карты должна отображаться карта 

**Критерий приемки**
```gherkin
Допустим я перешел на  страницу карты
То я вижу карту
```
**Оценка**
Планируемое время: 1 час

**Comment by WinkOne** [comment]
делал 3 часа
