### ISSUE TITLE
Написать тест на редактирование юзера

### ISSUE THREAD

**Issue by Ulan1983** [ESDP-JS-2020-1/caravan#46]
**Мотивация**
Необходимо написать тест на редактирование юзера

**Конечный результат**
При запуске теста на редактирование юзера запускается тест

**Критерий приемки**
```gherkin
Допустим я запускаю тест на редактирование юзера
То тест запускается без ошибок
```
**Оценка**
Планируемое время: 1 час

**Comment by Baytik** [comment]
заняло 40 мин
Код для запуска всех тестов (./test.sh)
Код для запуска отдельного теста (./test.sh --grep @Название теста)
