### ISSUE TITLE
Удалить ненужный код в файле steps.js

### ISSUE THREAD

**Issue by Ulan1983** [ESDP-JS-2020-1/caravan#47]
**Мотивация**
Необходимо отредактировать файл steps.js в тестах и удалить неиспользуемый или дублируемый код

**Конечный результат**
После редактирования файла steps.js и при запуске тестов запускаются функции

**Критерий приемки**
```gherkin
Допустим я запускаю тесты
То тесты запускаются без ошибок
```
**Оценка**
Планируемое время: 1 час

**Comment by Baytik** [comment]
заняло 1 час 10 мин
Код для запуска всех тестов (./test.sh)
Код для запуска отдельного теста (./test.sh --grep @Название теста)
