### ISSUE TITLE
Необходимо реализовать возможность выбора языка в приложении

### ISSUE THREAD

**Issue by Ulan1983** [ESDP-JS-2020-1/caravan#48]
**Мотивация**
Необходимо реализовать возможность выбора языка в приложении

**Конечный результат**
При использовании приложения есть возможность выбора языка

**Критерий приемки**
```gherkin
Допустим я залогинен как пользователь
И в header приложения вижу кнопку с выпадающим меню
Если я нажму на эту кнопку
То выбираю нужный мне язык
```
Оценка
Планируемое время: 3 часа

**Comment by KadyrPoyraz228337** [comment]
Закончил работу 1 час
