### ISSUE TITLE
Добавить в фикстуры больше данных

### ISSUE THREAD

**Issue by Ulan1983** [ESDP-JS-2020-1/caravan#51]
**Мотивация**
Необходимо добавить больше данных в фикстуры для более удобной работы с приложением

**Конечный результат**
При запуске фикстур загружаются как можно больше используемых данных в приложении

**Критерий приемки**
```gherkin
Допустим я набираю команду для загрузки фикстур
То фикстуры загружаются без ошибок
```
**Оценка**
Планируемое время: 30 минут

**Comment by KadyrPoyraz228337** [comment]
Закончил за 30 минут
