### ISSUE TITLE
Добавить на бэкенде во всех роутах блок try catch, переделать на бэке редактирование

### ISSUE THREAD

**Issue by Ulan1983** [ESDP-JS-2020-1/caravan#52]
**Мотивация**
Необходимо добавить блоки try catch в тех роутах, в которых этот блок не используется. Также нужно переделать редактирование сущностей на бэке в тех роутах, в которых используется метод updateOne

**Конечный результат**
Try catch используется везде где нужно. Метод updateOne не используется вообще.

**Оценка**
Планируемое время: 1 час

**Comment by KadyrPoyraz228337** [comment]
Закончил за 40 минут
