### ISSUE TITLE
Переделать компоненты-классы на хуки

### ISSUE THREAD

**Issue by Ulan1983** [ESDP-JS-2020-1/caravan#56]
**Мотивация**
Необходимо переделать на фронте компоненты-классы на хуки

**Конечный результат**
Все компоненты приложения написаны на хуках

Критерий приемки
```gherkin
Допустим я открываю любой компонент на фронтенде
То все компоненты написаны на хуках
```
**Оценка**
Планируемое время: 1 час

**Comment by KadyrPoyraz228337** [comment]
Закончил за 20 минут
