### ISSUE TITLE
На фронте нужно вынести стили в useStyles

### ISSUE THREAD

**Issue by Ulan1983** [ESDP-JS-2020-1/caravan#57]
**Мотивация**
Необходимо вынести стили в useStyles

**Конечный результат**
В каждом компоненте, где есть стили, они используются через useStyles

**Критерий приемки**
```gherkin
Допустим я открываю любой компонент на фронте
То я вижу что стили написаны через useStyles
```
**Оценка**
Планируемое время: 1,5 часа

**Comment by WinkOne** [comment]
сделал за 1,5 часа
