### ISSUE TITLE
Вынести конфигурацию multer в отдельный файл

### ISSUE THREAD

**Issue by Ulan1983** [ESDP-JS-2020-1/caravan#59]
**Мотивация**
На бэкенде необходимо вынести конфигурацию multer в отдельный файл и переделать импорты в тех роутах, где этот multer используется

**Конечный результат**
В роутах используется кастомный multer

Критерий приемки
```gherkin
Допустим я открываю нужный мне файл с роутом
То используется кастомный multer
```
**Оценка**
Планируемое время: 1 час

**Comment by Baytik** [comment]
заняло 3 часа времени
