### ISSUE TITLE
Добавление продуктов администратором!

### ISSUE THREAD

**Issue by spartakF300** [ESDP-JS-2020-1/caravan#6]
**Мотивация**
Необходимо сделать возможность добавления продуктов в базу данных.

**Конечный результат**
При переходи на страницу добавления продуктов должно отображаться форма добавления продуктов и кнопка добавить.

**Критерий приемки**
```gherkin
Допустим я перешел на страницу добавления продуктов.
И заполнил все поля.
То по нажатию на кнопку"добавить"  добавляется новый продукт 
И все поля формы обнуляются.
```
**Оценка**
Планируемое время: 4 часа

**Comment by KadyrPoyraz228337** [comment]
Закончили работу за 1.5 часа

**Comment by WinkOne** [comment]
Готово
