### ISSUE TITLE
Добавить слои на карту

### ISSUE THREAD

**Issue by Ulan1983** [ESDP-JS-2020-1/caravan#61]
**Мотивация**
Необходимо добавить слои на карту

**Конечный результат**
В карте можно переключаться между слоями

**Критерий приемки**
```gherkin
Допустим я вижу карту
То я имею возможность выбирать слои
```
**Оценка**
Планируемое время: 2 часа

**Comment by WinkOne** [comment]
Начал в 12 10 не справился, закончи Спартак в 15 20
