### ISSUE TITLE
Переделать тесты в связи с изменениями в приложении

### ISSUE THREAD

**Issue by Ulan1983** [ESDP-JS-2020-1/caravan#66]
**Мотивация**
Необходимо переделать тесты в связи с изменениями в приложении

**Конечный результат**
Тесты запускаются без ошибок

**Критерии приёмки**
```gherkin
Допустим я запускаю тесты
То тесты отрабатывают без ошибок
```
**Оценка**
Планируемое время: 1 час

**Comment by Baytik** [comment]
Заняло 50 мин
