### ISSUE TITLE
Создать список продуктов

### ISSUE THREAD

**Issue by KadyrPoyraz228337** [ESDP-JS-2020-1/caravan#7]
### Мотивация
Необходимо создать вывод списка добавленных продуктов

### Конечный результат 
Вывод списка продуктов с их количеством, ценой и названием, а так же кнопкой, ведущей на страницу редактирования отдельного продукта 

### Критерии приёмки 
```gherkin
Допустим я зарегистрирован как администратор
И нахожусь на главной странице
Тогда я вижу текст  "список продуктов"
И нажимаю на кнопку "#editProduct"
Тогда меня перекидывает на страницу редактирования отдельного продукта
```

### Оценка
Планируемое время 1.5 часа

**Comment by notanITspecialist** [comment]
Закончил выполнение
