### ISSUE TITLE
Написать тесты на удаление групп и удаление пользователей из групп

### ISSUE THREAD

**Issue by Baytik** [ESDP-JS-2020-1/caravan#71]
**Мотивация**
Необходимо написать тесты на удаление групп и удаление пользователей из групп

**Конечный результат**
При запуске тестов на удаление групп и удаление пользователей из групп, запускаются тесты

**Критерий приемки**
```gherkin
Допустим я запускаю тесты на удаление групп и удаление пользователей из групп
То тесты запускаются без ошибок
```
**Оценка**
Планируемое время: 1 час 30 мин

**Comment by WinkOne** [comment]
начал в 13 00 
закончил в 14 55
