### ISSUE TITLE
Написать тесты на добавление группы и добавление пользователей в группы

### ISSUE THREAD

**Issue by Baytik** [ESDP-JS-2020-1/caravan#72]
**Мотивация**
Необходимо написать тесты на добавление группы и добавление пользователей в группы

**Конечный результат**
При запуске тестов на добавление группы и добавление пользователей в группы, запускаются тесты

**Критерий приемки**
```gherkin
Допустим я запускаю тесты на добавление группы и добавление пользователей в группы
То тесты запускаются без ошибок
```
**Оценка**
Планируемое время: 2 часа

**Comment by WinkOne** [comment]
вы полнил за 10 мин
