### ISSUE TITLE
Сделать отображение аватарки пользователя при редактировании пользователя

### ISSUE THREAD

**Issue by Baytik** [ESDP-JS-2020-1/caravan#74]
**Мотивация**
Необходимо сделать отображение аватарки пользователя при редактировании пользователя

**Конечный результат**
Отображается аватарка пользователя при редактировании пользователя

**Критерии приёмки**
```gherkin
Допустим я нахожусь на странице списка пользователей
И нажимаю редактировать пользователя
И заполняю все поля формы
И нажимаю на кнопку "Редактировать"
То вижу что аватарка пользователя успешно изменилась
```
**Оценка**
Планируемое время: 30 мин

**Comment by Ulan1983** [comment]
Закончил за 15 минут
