### ISSUE TITLE
Полностью перевести приложение на киргизский язык

### ISSUE THREAD

**Issue by Baytik** [ESDP-JS-2020-1/caravan#76]
**Мотивация**
Необходимо полностью перевести приложение на киргизский язык

**Конечный результат**
Всё приложение можно выборочно увидеть и на киргизском языке

**Критерий приемки**
```gherkin
Допустим я залогинился
То я могу выборочно увидеть приложение и на киргизском языке
```
**Оценка**
Планируемое время: 5 часов

**Comment by Ulan1983** [comment]
Выполнил за 10 ч 30 мин
