### ISSUE TITLE
Исправить редактирование пользователя

### ISSUE THREAD

**Issue by Baytik** [ESDP-JS-2020-1/caravan#79]
**Мотивация**
Необходимо исправить редактирование пользователя

**Конечный результат**
При редактировании пользователя всё работает корректно и без ошибок

**Критерий приемки**
```gherkin
Допустим я редактирую пользователя
И заполняю поля формы
То вижу что пользователь изменён успешно
```
**Оценка**
Планируемое время: 1 час

**Comment by spartakF300** [comment]
закончил за 2:53
