### ISSUE TITLE
Переделать permit на отслеживание разрешений за место "ролей" и переделать приложение под изменения 

### ISSUE THREAD

**Issue by Baytik** [ESDP-JS-2020-1/caravan#81]
**Мотивация**
Необходимо переделать permit на отслеживание разрешений за место "ролей" и переделать приложение под изменения 

**Конечный результат**
Вся приложение работает без ошибок с новыми изменениями в permit

**Критерий приемки**
```gherkin
Допустим я захожу на приложение
То вижу успешную работу изменённого приложения 
```
**Оценка**
Планируемое время: 4 часа

**Comment by notanITspecialist** [comment]
12:40
13:31
