### ISSUE TITLE
Перенести ссылки из всплывающего меню в header на desktop версии сайта

### ISSUE THREAD

**Issue by Baytik** [ESDP-JS-2020-1/caravan#82]
**Мотивация**
Необходимо перенести ссылки из всплывающего меню в header на desktop версии сайта, для лучшего user experience

**Конечный результат**
При запуске сайта, ссылки из всплывающего меню, отображаются в хедере

**Критерий приемки**
```gherkin
Допустим я запускаю сайт
То вижу что ссылки из всплывающего меню, отображаются в хедере
```
**Оценка**
Планируемое время: 1 час

**Comment by KadyrPoyraz228337** [comment]
Выполнил за час
