### ISSUE TITLE
Исправить слова переведённые с русского на киргизский

### ISSUE THREAD

**Issue by Baytik** [ESDP-JS-2020-1/caravan#85]
**Мотивация**
Необходимо переделать слова переведённые с русского на киргизский
Слова которые нужно перевести:
Фото - Сүрөт
Список заявок - өтүнүч тизмеси
Подать заявку - өтүнүч берүү
Количество - Сан
Добавить новые продукты - Жаңы продуктарды кошуу
Роль - Кызматы
Наличие холодильника - Муздаткычтын болушу
Статус - даража
Создать заявку - өтүнүч түзүү

**Конечный результат**
При переводе все слова переводятся с русского на киргизский правильно

**Оценка**
Планируемое время: 1 час

**Comment by Ulan1983** [comment]
Закончил за 30 мин
