### ISSUE TITLE
Исправить не разрешенным действиям пользователя то перекидывать на логин

### ISSUE THREAD

**Issue by Baytik** [ESDP-JS-2020-1/caravan#88]
**Мотивация**
Необходимо переделать не разрешенным действиям пользователя то перекидывать на логин

**Конечный результат**
При входе в приложения не разрешённому пользователю тем или иным действиям, то перекидывать на логин

**Критерий приемки**
```gherkin
Допустим я захожу через пользователя к которому не разрешается делать те или иные действия 
То его перекидывает на логин
```
**Оценка**
Планируемое время: 4 часа

**Comment by spartakF300** [comment]
выполнил за 5 часов
