### ISSUE TITLE
Сделать поставку приложения на демо сервер

### ISSUE THREAD

**Issue by Baytik** [ESDP-JS-2020-1/caravan#90]
**Мотивация**
Необходимо сделать поставку приложения на демо сервер

**Конечный результат**
Поставка приложения на демо сервер

**Критерий приемки**
```gherkin
Допустим я захожу на демо сервер
То вижу наше приложение
```
**Оценка**
Планируемое время: 6 часа

**Comment by KadyrPoyraz228337** [comment]
Выполнил за 16 часов
