### ISSUE TITLE
Сделать router на beckend для получения статистики о продукте

### ISSUE THREAD

**Issue by notanITspecialist** [ESDP-JS-2020-1/caravan#94]
**Мотивация**
Необходимо сделать router на beckend для запроса статистики по нуждам пользователя

**Конечный результат**
Если сделать запрос по просмотру стратистики, будет прислана статистика по указанному продукту, путь должен выглядеть так "/stat/:id/:date" где id - _id продукта, а date - то за сколько дней вам нужна статистика ( если указать "7" то придет статистика за последние семь дней)

**Критерии приёмки**
```gherkin
Допустим я делаю запрос на путь `/stat/ ${product._id} /7` 
То придет статистика о продукте product._id за последнюю неделю
```
**Оценка**
Планируемое время: 3 час

**Comment by Baytik** [comment]
Закончил за 2 часа
