### ISSUE TITLE
Сделать систему отображение элементов страницы по пермишенам

### ISSUE THREAD

**Issue by notanITspecialist** [ESDP-JS-2020-1/caravan#95]
**Мотивация**
Необходимо сделать функцию checkPermission для отображение элементов страницы по передаваемому в эту функцию аргументу 

**Конечный результат**
Если я хочу отобразить кнопку "Редактировать" только для тех у кого есть permission "editProduct", то код будет выглядеть так ( {checkPermission("editProduct") && <button>Редактировать</button>} )

**Критерии приёмки**
```gherkin
Допустим я пользователь без пермишена "editProduct" 
Если для редактирования нужен пермишен "editProduct"
То кнопка "Редактировать" не будет отображатся
 ```
**Оценка**
Планируемое время: 4 час

**Comment by spartakF300** [comment]
потратил 3 часа
