### ISSUE TITLE
Сделать получение статистики о продукте

### ISSUE THREAD

**Issue by notanITspecialist** [ESDP-JS-2020-1/caravan#96]
**Мотивация**
Необходимо сделать получение статистики о продукте за последние 7 дней (по дефолту), у пользователя будет возможность выбрать количество дней по которым придет статистика, это будет отображаться в виде текстового поля в которое можно ввести цифру до 365, дата будет передаваться в строку запроса браузера в таком виде `/stat/ ${product_id}/ ${date} `, данные буду запрашиваться по рендеру страницы и отображаться в диаграмме   

**Конечный результат**
Пользователь с разрешением "getStatistic" может просматривать статистику у продукта, при переходе на страницу статистики я увижу поле для выбора даты до которой эту статистику показывать и статистику в виде диаграммы

**Критерии приёмки**
```gherkin
Допустим я пользователь пермишена "getStatistic" 
Если я нахожусь на странице "/"
И нажму на кнопку "Смотреть статистику"
То меня перекинет на страницу с отображенной статистикой
 ```
**Оценка**
Планируемое время: 4 час

**Comment by KadyrPoyraz228337** [comment]
Закончил за 3 часа
