### ISSUE TITLE
Сделать тип продукта при его создании

### ISSUE THREAD

**Issue by notanITspecialist** [ESDP-JS-2020-1/caravan#97]
**Мотивация**
Необходимо сделать дополнительное поле в модели Product, название поля - productType, там будет указан тип продукта и он должен быть обязательным, для поля amount сделать type: Number, на frontend в форме добавления продукта нужно добавить поле для типа продукта, а поле amount сделать только для ввода цифр

**Конечный результат**
Пользователь с разрешением "addProduct" может добавить новый продукт и указать тип для продукта, к примеру "Пачка 1кг"

**Критерии приёмки**
```gherkin
Допустим я пользователь с пермишеном "addProduct" 
Если я нахожусь на странице "/product/add"
И заполняю все поля формы
То будет будет создан новый продукт
 ```
**Оценка**
Планируемое время: 1 час

**Comment by Baytik** [comment]
Закончил за 50 мин
