### ISSUE TITLE
Сделать тест на закрытие заявки

### ISSUE THREAD

**Issue by notanITspecialist** [ESDP-JS-2020-1/caravan#99]
**Мотивация**
Необходимо сделать тест на закрытие заявки

**Конечный результат**
При запуске теста на закрытие заявки он отрабатывает коректно

**Критерии приёмки**
```gherkin
Допустим я пользователь с пермишеном "closeRequest" 
Если я нахожусь на странице `/requests/ ${request._id}`
И статус заявки ''performed"
И я нажимаю на кнопку "Закрыть заявку"
То статус заявки станет ''closed"
 ```
**Оценка**
Планируемое время: 2 час

**Comment by Baytik** [comment]
Заняло 15 мин
